apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: dotnetlinux
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: dotnetlinux
    spec:
      containers:
        - image: "brianfriedman/petstore"
          imagePullPolicy: Never
          name: dotnetlinux
        - image: "brianfriedman/auth-proxy"
          imagePullPolicy: Never
          name: auth-proxy
          ports:
            - containerPort: 80