/*
 * 
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace Petstore.GeneratedCode.Models
{ 
        /// <summary>
        /// pet status in the store
        /// </summary>
        /// <value>pet status in the store</value>
        
        public enum PetStatusEnum
        {
            /// <summary>
            /// Enum Available for available
            /// </summary>
            [EnumMember(Value = "available")]
            Available,
            /// <summary>
            /// Enum Pending for pending
            /// </summary>
            [EnumMember(Value = "pending")]
            Pending,
            /// <summary>
            /// Enum Sold for sold
            /// </summary>
            [EnumMember(Value = "sold")]
            Sold,
        }
}
